In [1]:
import numpy as np
from numpy import linalg as LA

Eigenvalues and eigenvectors

In [2]:
H = np.array([[3, 2], 
              [2, 1]])
LA.eig(H)
# Result matrix first row not positive (Eigenvalues) -> Saddle point

(array([ 4.23606798, -0.23606798]),
 array([[ 0.85065081, -0.52573111],
        [ 0.52573111,  0.85065081]]))

In [3]:
H = np.array([[5, 2], 
              [2, 1]])
LA.eig(H)
# Two eigenvalues are positive -> Minimizer

(array([5.82842712, 0.17157288]),
 array([[ 0.92387953, -0.38268343],
        [ 0.38268343,  0.92387953]]))